# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/parameters.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 250)
        Dialog.setMinimumSize(QtCore.QSize(550, 250))
        Dialog.setMaximumSize(QtCore.QSize(550, 250))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 59, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.comboBox_der_type = QtWidgets.QComboBox(Dialog)
        self.comboBox_der_type.setObjectName("comboBox_der_type")
        self.gridLayout.addWidget(self.comboBox_der_type, 1, 1, 1, 1)
        self.comboBox_dta_model = QtWidgets.QComboBox(Dialog)
        self.comboBox_dta_model.setObjectName("comboBox_dta_model")
        self.gridLayout.addWidget(self.comboBox_dta_model, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 59, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.comboBox_der_model = QtWidgets.QComboBox(Dialog)
        self.comboBox_der_model.setObjectName("comboBox_der_model")
        self.gridLayout.addWidget(self.comboBox_der_model, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 9, 0, 1, 2)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.spinBox_n_branch = QtWidgets.QSpinBox(Dialog)
        self.spinBox_n_branch.setProperty("value", 20)
        self.spinBox_n_branch.setObjectName("spinBox_n_branch")
        self.gridLayout.addWidget(self.spinBox_n_branch, 3, 1, 1, 1)
        self.spinBox_n_loop = QtWidgets.QSpinBox(Dialog)
        self.spinBox_n_loop.setMaximum(3)
        self.spinBox_n_loop.setProperty("value", 2)
        self.spinBox_n_loop.setObjectName("spinBox_n_loop")
        self.gridLayout.addWidget(self.spinBox_n_loop, 4, 1, 1, 1)
        self.doubleSpinBox_sim_filter = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_sim_filter.setMaximum(1.0)
        self.doubleSpinBox_sim_filter.setSingleStep(0.05)
        self.doubleSpinBox_sim_filter.setProperty("value", 0.5)
        self.doubleSpinBox_sim_filter.setObjectName("doubleSpinBox_sim_filter")
        self.gridLayout.addWidget(self.doubleSpinBox_sim_filter, 5, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        # self.label_5.setText(_translate("Dialog", "Derivative Number"))
        # self.label_2.setText(_translate("Dialog", "Derivative Type"))
        # self.label_3.setText(_translate("Dialog", "Derivative Loops"))
        # self.label.setText(_translate("Dialog", "Derivative Model"))
        # self.label_4.setText(_translate("Dialog", "DTA Prediction"))
        # self.label_6.setText(_translate("Dialog", "Derivative Similarity"))

        self.label_5.setText(_translate("Dialog", "Expansion Number"))
        self.label_2.setText(_translate("Dialog", "Compound Type"))
        self.label_3.setText(_translate("Dialog", "Iterations"))
        self.label.setText(_translate("Dialog", "Model type"))
        self.label_4.setText(_translate("Dialog", "DTA Prediction"))
        self.label_6.setText(_translate("Dialog", "Derivative Similarity"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
